#!/bin/bash

installroot=$1
osver=$2
arch=$3
profile=$4
workdir=$5

chroot $installroot bash -x << 'CHROOTED'
	rmdir /var/log/consoles/
	ln -sf /shared/consoles /var/log/consoles
CHROOTED
