#!/bin/bash

installroot=$1
osver=$2
arch=$3
profile=$4
workdir=$5

chroot $installroot bash -x << 'CHROOTED'
	rm -f /etc/localtime
	ln -s /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
CHROOTED
