#!/bin/sh
installroot=$1
osver=$2
arch=$3
profile=$4
workdir=$5

chroot $installroot bash -x << 'CHROOTED'
	systemctl enable dkms
	systemctl enable openafs-client
	if [ ! -L /msrc ]
	then
	        ln -s /afs/msrc.pnl.gov/files/ /msrc
	fi
CHROOTED
