#!/bin/sh
installroot=$1
osver=$2
arch=$3
profile=$4
workdir=$5

MSC_CLUSTER_NAME=`gettab key=msc_cluster_name site.value`

chroot $installroot bash -x << CHROOTED
	if ! grep -q '/msc' /etc/fstab
	then
		echo 'mscmsc:/export/msc     /msc   nfs  rw,nolock,_netdev,tcp,nfsvers=3,timeo=60,retrans=10,intr,noacl     0 0'  >> /etc/fstab
	fi

	if [ ! -e /msc ]
	then
		mkdir /msc
	fi

	ln -sf /msc/$MSC_CLUSTER_NAME /cluster
CHROOTED
