#!/bin/sh
installroot=$1
osver=$2
arch=$3
profile=$4
workdir=$5

chroot $installroot bash -x << 'CHROOTED'
	if ! grep -q '/home' /etc/fstab
	then
		echo 'mschome:/export/home     /home   nfs  rw,nolock,_netdev,tcp,nfsvers=3,timeo=60,retrans=10,intr,noacl     0 0' >> /etc/fstab
	fi
CHROOTED
