#!/bin/bash -x

installroot=$1
osver=$2
arch=$3
profile=$4
workdir=$5

MSC_CLUSTER_NAME=`gettab key=msc_cluster_name site.value`
cd /install/${MSC_CLUSTER_NAME}
./show_vers_log.sh > $installroot/etc/image-version.txt
